services:
  frontend:
    build:
      context: ./frontend
    container_name: booking_frontend
    restart: unless-stopped
    ports:
      - '127.0.0.1:5172:5172'
    command: ['npm', 'run', 'build']
